// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/book": {
            "put": {
                "description": "Создаёт новую заявку и связывает её с регионом",
                "description": "Создаёт новую заявку и добавляет в неё регион",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Бронирование"
                    "Бронирование"
                ],
                "summary": "Забронировать регион",
                "summary": "Забронировать регион",
                "parameters": [
                    {
                        "description": "Параметры запроса на бронирование",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ds.BookRegionRequestBody"
                        }
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/flight": {
            "get": {
                "description": "Возвращает заяввку с указанными параметрами",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Заявки"
                    "Заявки"
                ],
                "summary": "Получить заявку",
                "summary": "Получить заявку",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Статус заявки",
                        "description": "Статус заявки",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/flight/delete/{flight_id}": {
            "put": {
                "description": "Меняет статус заявки на \"Удалён\"",
                "description": "Меняет статус заявки на \"Удалён\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Заявки"
                    "Заявки"
                ],
                "summary": "Удалить заявку",
                "summary": "Удалить заявку",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id заявки",
                        "description": "id заявки",
                        "name": "flight_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/flight/edit": {
            "put": {
                "description": "Находит заявку и обновляет её поля",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Заявки"
                    "Заявки"
                ],
                "summary": "Отредактировать заявку",
                "parameters": [
                    {
                        "description": "Заявка",
                        "description": "Заявка",
                        "name": "flight",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/ds.Flight"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/flight/status_change": {
            "put": {
                "description": "Получает id заявки и новый статус и производит необходимые обновления",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Заявки"
                    "Заявки"
                ],
                "summary": "Изменить статус заявки",
                "parameters": [
                    {
                        "description": "Тело запроса",
                        "name": "request_body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ds.ChangeFlightStatusRequestBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/flight_to_region/delete": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Заявки"
                    "Заявки"
                ],
                "summary": "Удаляет связь региона с заявкой",
                "summary": "Удаляет связь региона с заявкой",
                "parameters": [
                    {
                        "description": "Тело запроса",
                        "name": "request_body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ds.DeleteFlightToRegionRequestBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/flights": {
            "get": {
                "description": "Возвращает список заявок",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Заявки"
                    "Заявки"
                ],
                "summary": "Получить заявки",
                "summary": "Получить заявки",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Статус заявок",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Возвращает jwt токен",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Аутентификация"
                    "Аутентификация"
                ],
                "summary": "Войти в систему",
                "parameters": [
                    {
                        "description": "Тело запроса на вход",
                        "name": "request_body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app.loginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.loginResp"
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Аутентификация"
                    "Аутентификация"
                ],
                "summary": "Выйти из системы",
                "summary": "Выйти из системы",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/region/add": {
            "put": {
                "description": "Создаёт новый регион с праметрами, описанными в json'е",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Регионы"
                    "Регионы"
                ],
                "summary": "Добавить регион в БД",
                "parameters": [
                    {
                        "description": "Данные нового регионы",
                        "name": "region",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ds.Region"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Регион был успешно создан",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/region/delete/{region_name}": {
            "put": {
                "description": "Находит регион по имени и меняет его статус на \"Недоступен\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Регионы"
                    "Регионы"
                ],
                "summary": "Удалить регион",
                "summary": "Удалить регион",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название региона",
                        "name": "region_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/region/delete_restore/{region_name}": {
            "get": {
                "description": "Меняет статус региона с \"Действует\" на \"Недоступен\" и наобороь",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Регионы"
                    "Регионы"
                ],
                "summary": "Удаляет или восстанавливает регион",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Имя региона",
                        "name": "region_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/region/edit": {
            "put": {
                "description": "Находит регион по имени и обновляет его поля",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Регионы"
                    "Регионы"
                ],
                "summary": "Отредактировать регион",
                "parameters": [
                    {
                        "description": "Новые данные изменяемого региона (должно быть имя региона или его id)",
                        "name": "region",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ds.Region"
                        }
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/region/{region}": {
            "get": {
                "description": "Возвращает регион по имени",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Регионы"
                    "Регионы"
                ],
                "summary": "Получить регион",
                "summary": "Получить регион",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Имя региона",
                        "name": "region",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/regions": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Регионы"
                    "Регионы"
                ],
                "summary": "Получить все регионы",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Паттерн имени региона",
                        "name": "name_pattern",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Округ",
                        "name": "district",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Статус региона (Действует/Недействителен)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": ""
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Добавляет нового пользователя в БД",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Аутентификация"
                    "Аутентификация"
                ],
                "summary": "Зарегистрировать нового пользователя",
                "summary": "Зарегистрировать нового пользователя",
                "parameters": [
                    {
                        "description": "Тело запроса",
                        "name": "request_body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app.registerReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.registerResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.loginReq": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "app.loginResp": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "token_type": {
                    "type": "string"
                }
            }
        },
        "app.registerReq": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "лучше назвать то же самое что login",
                    "type": "string"
                },
                "pass": {
                    "type": "string"
                }
            }
        },
        "app.registerResp": {
            "type": "object",
            "properties": {
                "ok": {
                    "type": "boolean"
                }
            }
        },
        "ds.BookRegionRequestBody": {
            "type": "object",
            "properties": {
                "arrivalDate": {
                    "type": "string"
                },
                "regionName": {
                    "type": "string"
                },
                "takeoffDate": {
                    "type": "string"
                }
            }
        },
        "ds.ChangeFlightStatusRequestBody": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "ds.DeleteFlightToRegionRequestBody": {
            "type": "object",
            "properties": {
                "flightID": {
                    "type": "integer"
                },
                "regionID": {
                    "type": "integer"
                }
            }
        },
        "ds.Flight": {
            "type": "object",
            "properties": {
                "arrivalDate": {
                    "type": "string"
                },
                "dateCreated": {
                    "type": "string"
                },
                "dateFinished": {
                    "type": "string"
                },
                "dateProcessed": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "moderator": {
                    "$ref": "#/definitions/ds.User"
                },
                "moderatorRefer": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "takeoffDate": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/ds.User"
                },
                "userRefer": {
                    "type": "string"
                }
            }
        },
        "ds.Region": {
            "type": "object",
            "properties": {
                "areaKm": {
                    "type": "number"
                },
                "averageHeightM": {
                    "type": "number"
                },
                "details": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "headEmail": {
                    "type": "string"
                },
                "headName": {
                    "type": "string"
                },
                "headPhone": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "population": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "ds.User": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "pass": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/role.Role"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "role.Role": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "Undefined",
                "User",
                "Moderator",
                "Admin"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0-0",
	Host:             "127.0.0.1:8000",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Заявки контроля маршрутов БПЛА",
	Description:      "",
	Title:            "Заявки контроля маршрутов БПЛА",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
